// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rollchains/tiablob/v1/genesis.proto

package tiablob

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	celestia "github.com/rollchains/tiablob/lightclients/celestia"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the rollchain module's genesis state.
type GenesisState struct {
	Validators []Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators"`
	// the height of the last block that was proven to be posted to Celestia.
	// increment only, never skipping heights.
	ProvenHeight         int64                  `protobuf:"varint,2,opt,name=proven_height,json=provenHeight,proto3" json:"proven_height,omitempty"`
	CelestiaGenesisState *celestia.GenesisState `protobuf:"bytes,3,opt,name=celestia_genesis_state,json=celestiaGenesisState,proto3" json:"celestia_genesis_state,omitempty"`
	PendingBlocks        []*BlockWithExpiration `protobuf:"bytes,4,rep,name=pending_blocks,json=pendingBlocks,proto3" json:"pending_blocks,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2bd6ea5db040ca7, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetValidators() []Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *GenesisState) GetProvenHeight() int64 {
	if m != nil {
		return m.ProvenHeight
	}
	return 0
}

func (m *GenesisState) GetCelestiaGenesisState() *celestia.GenesisState {
	if m != nil {
		return m.CelestiaGenesisState
	}
	return nil
}

func (m *GenesisState) GetPendingBlocks() []*BlockWithExpiration {
	if m != nil {
		return m.PendingBlocks
	}
	return nil
}

type UnprovenBlock struct {
	Height int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Block  []byte `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
}

func (m *UnprovenBlock) Reset()         { *m = UnprovenBlock{} }
func (m *UnprovenBlock) String() string { return proto.CompactTextString(m) }
func (*UnprovenBlock) ProtoMessage()    {}
func (*UnprovenBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2bd6ea5db040ca7, []int{1}
}
func (m *UnprovenBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnprovenBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnprovenBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnprovenBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnprovenBlock.Merge(m, src)
}
func (m *UnprovenBlock) XXX_Size() int {
	return m.Size()
}
func (m *UnprovenBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_UnprovenBlock.DiscardUnknown(m)
}

var xxx_messageInfo_UnprovenBlock proto.InternalMessageInfo

func (m *UnprovenBlock) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *UnprovenBlock) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "rollchains.tiablob.v1.GenesisState")
	proto.RegisterType((*UnprovenBlock)(nil), "rollchains.tiablob.v1.UnprovenBlock")
}

func init() {
	proto.RegisterFile("rollchains/tiablob/v1/genesis.proto", fileDescriptor_f2bd6ea5db040ca7)
}

var fileDescriptor_f2bd6ea5db040ca7 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x3f, 0x4f, 0xeb, 0x30,
	0x10, 0xc0, 0x93, 0xb6, 0xaf, 0x83, 0xdb, 0xbe, 0x21, 0xea, 0xab, 0xa2, 0x4a, 0x2f, 0x84, 0x56,
	0x48, 0x15, 0x83, 0xa3, 0x96, 0x01, 0x81, 0xc4, 0x52, 0x89, 0x3f, 0x2b, 0x41, 0x80, 0xc4, 0x12,
	0x25, 0xa9, 0x95, 0x58, 0x18, 0x3b, 0xc4, 0x6e, 0x04, 0xdf, 0x82, 0x6f, 0xc4, 0xda, 0xb1, 0x23,
	0x13, 0x42, 0xed, 0x17, 0x41, 0x71, 0x9c, 0x52, 0x44, 0xd8, 0xec, 0xf3, 0xef, 0xce, 0xf7, 0xbb,
	0x03, 0xc3, 0x94, 0x11, 0x12, 0xc6, 0x3e, 0xa6, 0xdc, 0x11, 0xd8, 0x0f, 0x08, 0x0b, 0x9c, 0x6c,
	0xec, 0x44, 0x88, 0x22, 0x8e, 0x39, 0x4c, 0x52, 0x26, 0x98, 0xf1, 0xef, 0x0b, 0x82, 0x0a, 0x82,
	0xd9, 0xb8, 0xdf, 0x8d, 0x58, 0xc4, 0x24, 0xe1, 0xe4, 0xa7, 0x02, 0xee, 0xef, 0x56, 0x57, 0x7c,
	0x9c, 0xa3, 0xf4, 0x59, 0x21, 0x7b, 0xd5, 0x48, 0xe6, 0x13, 0x3c, 0xf3, 0x05, 0x4b, 0x15, 0x76,
	0x5c, 0x81, 0x11, 0x1c, 0xc5, 0x22, 0x24, 0x18, 0x51, 0xc1, 0x9d, 0x10, 0x11, 0xc4, 0x05, 0xf6,
	0xf3, 0xe4, 0xf2, 0x5c, 0xe4, 0x0e, 0x5e, 0x6b, 0xa0, 0x7d, 0x5e, 0x48, 0x5c, 0x09, 0x5f, 0x20,
	0xe3, 0x0c, 0x80, 0x4d, 0x7d, 0x6e, 0xea, 0x76, 0x7d, 0xd4, 0x9a, 0xd8, 0xb0, 0x52, 0x0c, 0xde,
	0x94, 0xe0, 0xb4, 0xb1, 0x78, 0xdf, 0xd1, 0xdc, 0xad, 0x4c, 0x63, 0x08, 0x3a, 0x49, 0xca, 0x32,
	0x44, 0xbd, 0x18, 0xe5, 0xbd, 0x98, 0x35, 0x5b, 0x1f, 0xd5, 0xdd, 0x76, 0x11, 0xbc, 0x90, 0x31,
	0x83, 0x81, 0x5e, 0xd9, 0x8f, 0xa7, 0x46, 0xe9, 0xf1, 0xbc, 0x0d, 0xb3, 0x6e, 0xeb, 0xa3, 0xd6,
	0xe4, 0xa8, 0xea, 0xe3, 0x6d, 0x35, 0xb8, 0xd1, 0xc9, 0xc6, 0x70, 0xdb, 0xc3, 0xed, 0x96, 0x2f,
	0xdf, 0xec, 0x2e, 0xc1, 0xdf, 0x04, 0xd1, 0x19, 0xa6, 0x91, 0x17, 0x10, 0x16, 0xde, 0x73, 0xb3,
	0x21, 0x0d, 0xf7, 0x7f, 0x31, 0x9c, 0xe6, 0xd0, 0x2d, 0x16, 0xf1, 0xe9, 0x53, 0x82, 0x53, 0x5f,
	0x60, 0x46, 0xdd, 0x8e, 0xaa, 0x20, 0xdf, 0xf8, 0xe0, 0x04, 0x74, 0xae, 0x69, 0x61, 0x25, 0x23,
	0x46, 0x0f, 0x34, 0x95, 0xb2, 0x2e, 0x95, 0xd5, 0xcd, 0xe8, 0x82, 0x3f, 0xf2, 0x4f, 0x39, 0x89,
	0xb6, 0x5b, 0x5c, 0xa6, 0x87, 0x8b, 0x95, 0xa5, 0x2f, 0x57, 0x96, 0xfe, 0xb1, 0xb2, 0xf4, 0x97,
	0xb5, 0xa5, 0x2d, 0xd7, 0x96, 0xf6, 0xb6, 0xb6, 0xb4, 0xbb, 0xff, 0x11, 0x16, 0xf1, 0x3c, 0x80,
	0x21, 0x7b, 0x70, 0x7e, 0x6e, 0x38, 0x68, 0xca, 0x05, 0x1e, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x39, 0xbd, 0xfe, 0x29, 0x9a, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PendingBlocks) > 0 {
		for iNdEx := len(m.PendingBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.CelestiaGenesisState != nil {
		{
			size, err := m.CelestiaGenesisState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ProvenHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ProvenHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *UnprovenBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnprovenBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnprovenBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Block) > 0 {
		i -= len(m.Block)
		copy(dAtA[i:], m.Block)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Block)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ProvenHeight != 0 {
		n += 1 + sovGenesis(uint64(m.ProvenHeight))
	}
	if m.CelestiaGenesisState != nil {
		l = m.CelestiaGenesisState.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.PendingBlocks) > 0 {
		for _, e := range m.PendingBlocks {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *UnprovenBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovGenesis(uint64(m.Height))
	}
	l = len(m.Block)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, Validator{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProvenHeight", wireType)
			}
			m.ProvenHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProvenHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CelestiaGenesisState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CelestiaGenesisState == nil {
				m.CelestiaGenesisState = &celestia.GenesisState{}
			}
			if err := m.CelestiaGenesisState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingBlocks = append(m.PendingBlocks, &BlockWithExpiration{})
			if err := m.PendingBlocks[len(m.PendingBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnprovenBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnprovenBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnprovenBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Block = append(m.Block[:0], dAtA[iNdEx:postIndex]...)
			if m.Block == nil {
				m.Block = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
