// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: rollchains/tiablob/v1/tx.proto

package tiablobv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_SetCelestiaAddress_FullMethodName = "/rollchains.tiablob.v1.Msg/SetCelestiaAddress"
	Msg_InjectedData_FullMethodName       = "/rollchains.tiablob.v1.Msg/InjectedData"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// SetCelestiaAddress allows a validator to configure their Celestia address for feegranting
	SetCelestiaAddress(ctx context.Context, in *MsgSetCelestiaAddress, opts ...grpc.CallOption) (*MsgSetCelestiaAddressResponse, error)
	InjectedData(ctx context.Context, in *MsgInjectedData, opts ...grpc.CallOption) (*MsgInjectedDataResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetCelestiaAddress(ctx context.Context, in *MsgSetCelestiaAddress, opts ...grpc.CallOption) (*MsgSetCelestiaAddressResponse, error) {
	out := new(MsgSetCelestiaAddressResponse)
	err := c.cc.Invoke(ctx, Msg_SetCelestiaAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InjectedData(ctx context.Context, in *MsgInjectedData, opts ...grpc.CallOption) (*MsgInjectedDataResponse, error) {
	out := new(MsgInjectedDataResponse)
	err := c.cc.Invoke(ctx, Msg_InjectedData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// SetCelestiaAddress allows a validator to configure their Celestia address for feegranting
	SetCelestiaAddress(context.Context, *MsgSetCelestiaAddress) (*MsgSetCelestiaAddressResponse, error)
	InjectedData(context.Context, *MsgInjectedData) (*MsgInjectedDataResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) SetCelestiaAddress(context.Context, *MsgSetCelestiaAddress) (*MsgSetCelestiaAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCelestiaAddress not implemented")
}
func (UnimplementedMsgServer) InjectedData(context.Context, *MsgInjectedData) (*MsgInjectedDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectedData not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_SetCelestiaAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetCelestiaAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetCelestiaAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetCelestiaAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetCelestiaAddress(ctx, req.(*MsgSetCelestiaAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InjectedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInjectedData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InjectedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_InjectedData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InjectedData(ctx, req.(*MsgInjectedData))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rollchains.tiablob.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetCelestiaAddress",
			Handler:    _Msg_SetCelestiaAddress_Handler,
		},
		{
			MethodName: "InjectedData",
			Handler:    _Msg_InjectedData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollchains/tiablob/v1/tx.proto",
}
